# Generated by Django 5.2.17 on 2026-09-25 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('telegram_thread_id', models.BigIntegerField(blank=True, null=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interpello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interpelli', to='interpelli.province')),
            ],
            options={
                'ordering': ['-published_date', '-pk'],
            },
        ),
    ]
